<?php



/**
 * Skeleton subclass for performing query and update operations on the 'sf_beta_invite' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Mon Mar 21 12:21:14 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfBetaInvitePlugin.lib.model
 */
class PluginsfBetaInviteQuery extends BasesfBetaInviteQuery {

} // sfBetaInviteQuery
