<?php



/**
 * Skeleton subclass for representing a row from the 'sf_beta_invite' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.5.6 on:
 *
 * Mon Mar 21 12:21:14 2011
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    propel.generator.plugins.sfBetaInvitePlugin.lib.model
 */
class PluginsfBetaInvite extends BasesfBetaInvite 
{
  public function getNameOrEmail()
  {
    return strlen($this->getName()) > 0 ? $this->getName() : $this->getEmail();
  }
}
